"""
This type stub file was generated by pyright.
"""

class ReadOptions:
    ...


class ParseOptions:
    ...


class ConvertOptions:
    ...


def read_csv(input_file, read_options=None, parse_options=None, convert_options=None, memory_pool=None):
    ...
