"""
This type stub file was generated by pyright.
"""

import contextlib

TF_PLASMA_OP_PATH = ...
tf_plasma_op = ...
def load_plasma_tensorflow_op(): # -> None:
    ...

def build_plasma_tensorflow_op(): # -> None:
    ...

@contextlib.contextmanager
def start_plasma_store(plasma_store_memory, use_valgrind=..., use_profiler=..., plasma_directory=..., use_hugepages=..., external_store=...): # -> Generator[tuple[str, Popen[bytes]], None, None]:
    """
    Start a plasma store process.

    Parameters
    ----------
    plasma_store_memory : int
        Capacity of the plasma store in bytes.
    use_valgrind : bool
        True if the plasma store should be started inside of valgrind. If this
        is True, use_profiler must be False.
    use_profiler : bool
        True if the plasma store should be started inside a profiler. If this
        is True, use_valgrind must be False.
    plasma_directory : str
        Directory where plasma memory mapped files will be stored.
    use_hugepages : bool
        True if the plasma store should use huge pages.
    external_store : str
        External store to use for evicted objects.

    Returns
    -------
    result : (str, subprocess.Popen)
        A tuple of the name of the plasma store socket and the process ID of
        the plasma store process.
    """
    ...

