"""
This type stub file was generated by pyright.
"""

def register_torch_serialization_handlers(serialization_context): # -> None:
    ...

def register_default_serialization_handlers(serialization_context): # -> None:
    ...

def default_serialization_context():
    ...

