"""
This type stub file was generated by pyright.
"""

_DEPR_MSG = ...
def implements(f): # -> (g: Unknown) -> Unknown:
    ...

def product(seq): # -> int:
    """
    Return a product of sequence items.
    """
    ...

def get_contiguous_span(shape, strides, itemsize): # -> tuple[Unknown | Literal[0], Unknown | Literal[0]]:
    """
    Return a contiguous span of N-D array data.

    Parameters
    ----------
    shape : tuple
    strides : tuple
    itemsize : int
      Specify array shape data

    Returns
    -------
    start, end : int
      The span end points.
    """
    ...

def find_free_port(): # -> _RetAddress:
    ...

def guid(): # -> str:
    ...

